<h3>1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [3]:
import numpy as np
arr = np.array([0,1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


<h3>2. Given a NumPy array 'arr', check if its data type is float64.

In [5]:
import numpy as np

# taken an array
arr = np.array([1.0, 2.0, 3.0])

# Check if the data type is float64
if arr.dtype == np.float64:
    print("Its datatype is float64")
else:
    print("Its data type is not float64")


Its datatype is float64


<h3>3. Create a NumPy array 'arr' witha data type of complex128 containing three complex numbers.

In [6]:
import numpy as np

# Creating the array with complex numbers
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

print(arr)


[1.+2.j 3.+4.j 5.+6.j]


<h3>4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [7]:
import numpy as np

# Assuming 'arr' is existing NumPy array of integers
arr = np.array([1, 2, 3, 4, 5])

# Convert 'arr' to float32
arr_float32 = arr.astype(np.float32)

print(arr_float32)

[1. 2. 3. 4. 5.]


<h3>5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [8]:
import numpy as np
# Assuming 'arr' is your existing NumPy array with float64 data type
arr = np.array([1.123456789, 2.987654321, 3.456789123], dtype=np.float64)

# Convert 'arr' to float32
arr_float32 = arr.astype(np.float32)

print(arr_float32)

[1.1234568 2.9876542 3.456789 ]


<h3>6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data.

In [12]:
import numpy as np

def array_attributes():
    # Prompt the user to input the elements of the array
    user_input = input("Enter the elements of the array separated by spaces: ")
    
    # Convert the input string to a list of floats
    arr_list = list(map(float, user_input.split()))
    
    # Convert the list to a NumPy array
    arr = np.array(arr_list)
    
    # Get the shape, size, and data type of the array
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    
    return shape, size, dtype

# Example usage
shape, size, dtype = array_attributes()
print(f"Shape: {shape}, Size: {size}, Data type: {dtype}")


Enter the elements of the array separated by spaces:  11 22 33


Shape: (3,), Size: 3, Data type: float64


<h3>7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [25]:
import numpy as np
def array_dimension():
    arr = np.array([[1,2,3,4,
                    5,4,6,7]])
    
    dimension = arr.ndim
    
    return dimension

dimension = array_dimension()
print("Domension:",dimension)

Domension: 2


<h3>8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.<h3>

In [26]:
import numpy as np

def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size

# Example usage
arr = np.array([1.0, 2.0, 3.0, 4.0, 5.0], dtype=np.float64)
item_size, total_size = item_size_info(arr)
print(f"Item size: {item_size} bytes, Total size: {total_size} bytes")


Item size: 8 bytes, Total size: 40 bytes


<h3>9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.<h3>

In [27]:
import numpy as np

def array_strides(arr):
    return arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
strides = array_strides(arr)
print(f"Strides: {strides}")


Strides: (24, 8)


<h3>10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.<h3>

In [31]:
import numpy as np 
def shape_stride_relationship():
    arr = np.array([1,2,3,4,5,6,7])
    stride = arr.strides
    shape = arr.shape
    return stride, shape
stride, shape = shape_stride_relationship()
print(f"Strides: {stride} , shape: {shape}")

Strides: (8,) , shape: (7,)


<h3>11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.<h3>

In [39]:
import numpy as np
def create_zeros_array(n):
    return np.zeros(n)
n = 6
zero_array = create_zeros_array(n)
print(zero_array)

[0. 0. 0. 0. 0. 0.]


<h3>12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.<h3>

In [47]:
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

# Example usage
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


<h3>13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.<h3>

In [49]:
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print(range_array)

[0 2 4 6 8]


<h3>14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).<h3>

In [54]:
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)
start = 0.0
stop = 10.0
num = 4
linespace_array = generate_linear_space(start, stop, num)
print(linespace_array)

[ 0.          3.33333333  6.66666667 10.        ]


<h3>15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.<h3>

In [55]:
import numpy
def create_identity_matrix(n):
    return numpy.eye(n)
n = 3
identity_matrix = create_identity_matrix(n)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<h3>16. Write a function that takes a Python list and converts it into a NumPy array.<h3>

In [56]:
import numpy as np
def list_to_numpy_array(input_list):
    return np.array(input_list)

input_list = [1, 2, 3, 4, 5, 6]
numpy_array = list_to_numpy_array(input_list)
print(numpy_array)

[1 2 3 4 5 6]


<h3>17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.<h3>

In [57]:
import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5], dtype=np.int32)

# Create a view of the original array
view_array = original_array.view()

# Print both arrays to show they share the same data
print("Original array:", original_array)
print("View array:", view_array)

# Modify the view array
view_array[0] = 10

# Print both arrays again to show the change is reflected in both
print("Modified original array:", original_array)
print("Modified view array:", view_array)


Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]
Modified original array: [10  2  3  4  5]
Modified view array: [10  2  3  4  5]


<h3>18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.<h3>

In [58]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
concatenated_array_0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0:\n", concatenated_array_0)

# Concatenate along axis 1 (columns)
concatenated_array_1 = concatenate_arrays(arr1, arr2, axis=1)
print("Concatenated along axis 1:\n", concatenated_array_1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


<h3>19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [63]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[5,4],[6,4]])

concatenate_array = np.concatenate((arr1,arr2), axis=1)
print("Array 1:\n", arr1)
print("Array 2:\n",arr2)
print("concatenate array:\n",concatenate_array)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[5 4]
 [6 4]]
concatenate array:
 [[1 2 3 5 4]
 [4 5 6 6 4]]


<h3>20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [64]:
import numpy as np

def vertical_stack_arrays(arr_list):
    return np.vstack(arr_list)

# Example usage
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

# List of arrays to stack
arrays_to_stack = [arr1, arr2, arr3]

# Vertically stack the arrays
stacked_array = vertical_stack_arrays(arrays_to_stack)
print("Stacked array:\n", stacked_array)

Stacked array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


<h3>21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [65]:
import numpy as np

def create_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

# Example usage
start = 0
stop = 10
step = 2
range_array = create_range_array(start, stop, step)
print(range_array)


[ 0  2  4  6  8 10]


<h3>22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [66]:
import numpy as np
def generate_equally_spaced_values():
    return np.linspace(0, 1, 10)
equally_space_value = generate_equally_spaced_values()
print(equally_space_value)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


<h3>23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [67]:
import numpy as np
def logarithmically_spaced_values():
    return np.logspace(0, 3, num=5)

logarithmically_spaced_array = logarithmically_spaced_values()
print(logarithmically_spaced_array)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


<h3>24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [1]:
import numpy as np
import pandas as pd

# Create a NumPy array with random integers between 1 and 100
data = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame from the NumPy array
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])

# Display the DataFrame
print(df)


   Column1  Column2  Column3
0       90       41       72
1       91       46       98
2       83       63        9
3       32       79        5
4       18       82        7


<h3>25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [8]:
import pandas as pd
# creating data frame
df = pd.DataFrame({'a':[6,-3,5,-4], 'b':[-3,5,7,-2]})
# replace negative values with zero
df[ df<0 ] = 0
df

a  b
0  6  0
1  0  5
2  5  7
3  0  0

<h3>26. Access the 3rd element from the given NumPy array.

In [68]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

<h3>27. Retrieve the element at index (1, 2) from the 2D NumPy array.

In [77]:
import numpy as np

# Create a 2D NumPy array
arr_2d = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Retrieve the element at index (1, 2)
element = arr_2d[1, 2]

print(f"Element at index (1, 2): {element}")


Element at index (1, 2): 60


<h3>28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [74]:
import numpy as np
arr = np.array([3, 8, 2, 10, 5, 7])
# Use boolean indexing to extract elements greater than 5
greater_than_five = arr[arr > 5]

print(greater_than_five)

[ 8 10  7]


<h3>29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

In [75]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extract elements from index 2 to 5 (inclusive)
sliced_array = arr[2:6]

print(sliced_array)

[3 4 5 6]


<h3>30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [78]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]

print(sub_array)

[[2 3]
 [5 6]]


<h3>31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [10]:
import numpy as np

# Given 2D array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Indices to extract elements from arr
indices = np.array([[0, 1],  # arr[0, 1] -> 20
                    [2, 2],  # arr[2, 2] -> 90
                    [1, 0]]) # arr[1, 0] -> 40

# Extract elements using the indices
extracted_elements = arr[indices[:, 0], indices[:, 1]]

# Display the extracted elements
print("Extracted elements:")
print(extracted_elements)


Extracted elements:
[20 90 40]


<h3>32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using 
boolean indexing.

In [116]:
import numpy as np

def filter_greater_than(arr, threshold):
    # Ensure arr is a NumPy array
    arr = np.asarray(arr)
    
    # Apply boolean indexing to filter elements
    return arr[arr > threshold]

# Create a 1D array
arr = np.array([10, 25, 35, 45, 50, 60])

# Define the threshold
threshold = 30

# Filter elements greater than the threshold
filtered_elements = filter_greater_than(arr, threshold)

print("Original array:")
print(arr)

print("\nFiltered elements greater than threshold:")
print(filtered_elements)


Original array:
[10 25 35 45 50 60]

Filtered elements greater than threshold:
[35 45 50 60]


<h3> 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three 
separate arrays for each dimension.

In [115]:
import numpy as np

def extract_elements_3d(arr, row_indices, col_indices, depth_indices):
   # Ensure indices are NumPy arrays
    row_indices = np.asarray(row_indices)
    col_indices = np.asarray(col_indices)
    depth_indices = np.asarray(depth_indices)
    
    # Use advanced indexing to extract elements
    return arr[depth_indices, row_indices, col_indices]

# Create a 3D array with shape (3, 4, 5)
arr = np.array([[[ 1,  2,  3,  4,  5],
                 [ 6,  7,  8,  9, 10],
                 [11, 12, 13, 14, 15],
                 [16, 17, 18, 19, 20]],
                
                [[21, 22, 23, 24, 25],
                 [26, 27, 28, 29, 30],
                 [31, 32, 33, 34, 35],
                 [36, 37, 38, 39, 40]],
                
                [[41, 42, 43, 44, 45],
                 [46, 47, 48, 49, 50],
                 [51, 52, 53, 54, 55],
                 [56, 57, 58, 59, 60]]])

# Indices for each dimension
depth_indices = np.array([0, 1, 2])
row_indices = np.array([0, 1, 2])
col_indices = np.array([4, 3, 2])

# Extract elements
extracted_elements = extract_elements_3d(arr, row_indices, col_indices, depth_indices)

print("Original array:")
print(arr)

print("\nExtracted elements:")
print(extracted_elements)


Original array:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]

Extracted elements:
[ 5 29 53]


<h3> 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied 
using boolean indexing.

In [114]:
import numpy as np

def filter_elements(arr, condition1, condition2):
   # Ensure conditions are boolean arrays
    condition1 = np.asarray(condition1, dtype=bool)
    condition2 = np.asarray(condition2, dtype=bool)
    
    # Combine conditions using logical AND
    combined_condition = condition1 & condition2
    
    # Apply combined condition to the array
    return arr[combined_condition]

# Create an array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Define two conditions
condition1 = (arr > 20)   # Elements greater than 20
condition2 = (arr < 70)   # Elements less than 70

# Filter elements where both conditions are satisfied
filtered_elements = filter_elements(arr, condition1, condition2)

print("Original array:")
print(arr)

print("\nFiltered elements where both conditions are satisfied:")
print(filtered_elements)

Original array:
[10 20 30 40 50 60 70 80 90]

Filtered elements where both conditions are satisfied:
[30 40 50 60]


<h3> 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided 
in separate arrays.

In [113]:
import numpy as np

def extract_elements(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

# Create a 2D array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Row and column indices
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

# Extract elements
extracted_elements = extract_elements(arr, row_indices, col_indices)

print("Original array:")
print(arr)

print("\nRow indices:")
print(row_indices)

print("\nColumn indices:")
print(col_indices)

print("\nExtracted elements:")
print(extracted_elements)


Original array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Row indices:
[0 1 2]

Column indices:
[1 2 0]

Extracted elements:
[20 60 70]


<h3> 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.


In [112]:
import numpy as np

# Create the array with shape (3, 3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Scalar value to add
scalar = 5

# Add the scalar to each element in the array
result = arr + scalar

# Print the result
print("Original array:")
print(arr)

print("\nResult after adding scalar value:")
print(result)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Result after adding scalar value:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


<h3> 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [111]:
import numpy as np

# Create the arrays
arr1 = np.array([[2, 3, 4]])  # Shape (1, 3)
arr2 = np.array([[1, 2, 3, 4],  # Shape (3, 4)
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

# Reshape arr1 to be compatible for broadcasting
arr1_broadcasted = arr1.T  # Transpose to shape (3, 1)

# Perform the multiplication using broadcasting
result = arr2 * arr1_broadcasted

# Print the result
print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nResult of multiplication using broadcasting:")
print(result)


Array 1:
[[2 3 4]]

Array 2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result of multiplication using broadcasting:
[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


<h3> 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [110]:
import numpy as np

# Create the arrays
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[10, 20, 30],    # Shape (4, 3)
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])

# Adjust arr1 to match the shape of arr2 for broadcasting
# Since arr2 has 3 columns, we need to adjust arr1 to shape (4, 3)
# We will use slicing to match the dimensions
arr1_broadcasted = arr1[:, :3]  # Shape (1, 3)

# Perform the addition using broadcasting
result = arr2 + arr1_broadcasted

# Print the result
print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nResult of addition using broadcasting:")
print(result)

Array 1:
[[1 2 3 4]]

Array 2:
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]

Result of addition using broadcasting:
[[ 11  22  33]
 [ 41  52  63]
 [ 71  82  93]
 [101 112 123]]


<h3> 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [109]:
import numpy as np

# Create the arrays
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([[4, 5, 6]])      # Shape (1, 3)

# Perform the addition using broadcasting
result = arr1 + arr2

# Print the result
print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nResult of addition using broadcasting:")
print(result)


Array 1:
[[1]
 [2]
 [3]]

Array 2:
[[4 5 6]]

Result of addition using broadcasting:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


<h3> 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy 
broadcasting. Handle the shape incompatibility.

In [108]:
import numpy as np

# Create the arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10, 20]])  # Shape (1, 2) to be broadcasted over (2, 3)

# Reshape arr2 to make it broadcastable with arr1
# We want arr2 to be broadcasted along the rows of arr1
arr2_broadcasted = arr2.reshape(1, 2)  # Shape (1, 2)

# Perform the multiplication with broadcasting
result = arr1[:, :2] * arr2_broadcasted  # Use slicing to match shapes

# Print the result
print("Array 1:")
print(arr1)

print("\nArray 2 (reshaped for broadcasting):")
print(arr2_broadcasted)

print("\nResult of element-wise multiplication:")
print(result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2 (reshaped for broadcasting):
[[10 20]]

Result of element-wise multiplication:
[[ 10  40]
 [ 40 100]]


<h3> 41. Calculate column wise mean for the given array:
<h3> arr = np.array([[1, 2, 3], [4, 5, 6]])

In [103]:
import numpy as np

# Create the array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Calculate the column-wise mean
column_means = np.mean(arr, axis=0)

# Print the result
print("Original array:")
print(arr)

print("\nColumn-wise means:")
print(column_means)


Original array:
[[1 2 3]
 [4 5 6]]

Column-wise means:
[2.5 3.5 4.5]


<h3> 42. Find maximum value in each row of the given array:
<h3> arr = np.array([[1, 2, 3], [4, 5, 6]])

In [102]:
import numpy as np

# Create the array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Find the indices of the maximum values in each column
indices_of_max = np.argmax(arr, axis=1)

# Print the result
print("Original array:")
print(arr)

print("\nIndices of maximum values in each rows:")
print(indices_of_max)

Original array:
[[1 2 3]
 [4 5 6]]

Indices of maximum values in each rows:
[2 2]


<h3> 43. For the given array, find indices of maximum value in each column.
<h3> arr = np.array([[1, 2, 3], [4, 5, 6]])


In [100]:
import numpy as np

# Create the array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Find the indices of the maximum values in each column
indices_of_max = np.argmax(arr, axis=0)

# Print the result
print("Original array:")
print(arr)

print("\nIndices of maximum values in each column:")
print(indices_of_max)

Original array:
[[1 2 3]
 [4 5 6]]

Indices of maximum values in each column:
[1 1 1]


<h3> 44. For the given array, apply custom function to calculate moving sum along rows.
<h3> arr = np.array([[1, 2, 3], [4, 5, 6]])

In [99]:
import numpy as np

def moving_sum(arr, window_size):
    result = np.zeros((arr.shape[0], arr.shape[1] - window_size + 1), dtype=int)
    
    # Iterate over rows
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1] - window_size + 1):
            result[i, j] = np.sum(arr[i, j:j + window_size])
    
    return result

# Create the array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Define the window size
window_size = 2

# Calculate moving sum
moving_sums = moving_sum(arr, window_size)

# Print the result
print("Original array:")
print(arr)

print("\nMoving sum with window size", window_size, ":")
print(moving_sums)

Original array:
[[1 2 3]
 [4 5 6]]

Moving sum with window size 2 :
[[ 3  5]
 [ 9 11]]


<h3>45. In the given array, check if all elements in each column are even.
<h3>arr = np.array([[2, 4, 6], [3, 5, 7]])

In [98]:
import numpy as np

# Create the array
arr = np.array([[2, 4, 6], [3, 5, 7]])

# Check if all elements are even
all_even = (arr % 2 == 0)

# Check if all elements in each column are even
columns_all_even = np.all(all_even, axis=0)

# Print the result
print("Original array:")
print(arr)

print("\nAll elements even in each column:")
print(columns_all_even)

Original array:
[[2 4 6]
 [3 5 7]]

All elements even in each column:
[False False False]


<h3> 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
    <h3> original_array = np.array([1, 2, 3, 4, 5, 6])

In [95]:
import numpy as np

def reshape_array(array, m, n):
    reshaped_matrix = array.reshape(m, n) # Reshape the array to the specified dimensions
    return reshaped_matrix

# Create the original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Specify the dimensions for reshaping
m = 2  # Number of rows
n = 3  # Number of columns

# Reshape the array
reshaped_matrix = reshape_array(original_array, m, n)

# Print the result
print("Original array:")
print(original_array)

print("\nReshaped matrix:")
print(reshaped_matrix)


Original array:
[1 2 3 4 5 6]

Reshaped matrix:
[[1 2 3]
 [4 5 6]]


<h3> 47. Create a function that takes a matrix as input and returns the flattened array.
<h3>input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [94]:
import numpy as np

def flatten_matrix(matrix):
    flattened_array = matrix.flatten()  # Flatten the matrix to a one-dimensional array
    return flattened_array

# Create the input matrix
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Flatten the matrix
result = flatten_matrix(input_matrix)

# Print the result
print("Input matrix:")
print(input_matrix)

print("\nFlattened array:")
print(result)


Input matrix:
[[1 2 3]
 [4 5 6]]

Flattened array:
[1 2 3 4 5 6]


<h3> 48. Write a function that concatenates two given arrays along a specified axis.
<h3>array1 = np.array([[1, 2], [3, 4]])
<h3>array2 = np.array([[5, 6], [7, 8]])

In [93]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
array1 = np.array([[1, 2], [3, 4]]) 
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
concatenated_array_0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0:\n", concatenated_array_0)

# Concatenate along axis 1 (columns)
concatenated_array_1 = concatenate_arrays(arr1, arr2, axis=1)
print("\nConcatenated along axis 1:\n", concatenated_array_1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


<h3> 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
<h3> original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [90]:
import numpy as np

# Create the original array
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Define the number of splits and axis
num_splits = 3
axis = 0  # Split along columns

# Use np.array_split to split the array along the specified axis
sub_arrays = np.array_split(original_array, num_splits, axis=axis)

# Print the result
print("Original array:")
print(original_array)

print("\nSub-arrays after splitting:")
for i, sub_array in enumerate(sub_arrays):
    print(f"Sub-array {i}:")
    print(sub_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sub-arrays after splitting:
Sub-array 0:
[[1 2 3]]
Sub-array 1:
[[4 5 6]]
Sub-array 2:
[[7 8 9]]


<h3>50. Write a function that inserts and then deletes elements from a given array at specified indices.
<h3>original_array = np.array([1, 2, 3, 4, 5])
<h3>indices_to_insert = [2, 4]
<h3>values_to_insert = [10, 11]
<h3>indices_to_delete = [1, 3]

In [88]:
#used chatgpt to solve this question
import numpy as np

def modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Convert indices to insert and values to insert to NumPy arrays
    indices_to_insert = np.array(indices_to_insert)
    values_to_insert = np.array(values_to_insert)
    
    # Insert values into the original array
    # Use np.insert to insert values into the array at specified indices
    array_after_insertion = np.insert(original_array, indices_to_insert, values_to_insert)
    
    # Sort indices to delete in descending order to avoid index shifting issues
    indices_to_delete = sorted(indices_to_delete, reverse=True)
    
    # Delete elements from the array
    # Use np.delete to remove elements at specified indices
    final_array = np.delete(array_after_insertion, indices_to_delete)
    
    return final_array

# Original array
original_array = np.array([1, 2, 3, 4, 5])

# Indices and values to insert
indices_to_insert = [2, 4]
values_to_insert = [10, 11]

# Indices to delete
indices_to_delete = [1, 3]

# Modify the array
result_array = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)

# Print the result
print("Original array:")
print(original_array)

print("\nArray after insertion and deletion:")
print(result_array)


Original array:
[1 2 3 4 5]

Array after insertion and deletion:
[ 1 10  4 11  5]


<h3>51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [87]:
import numpy as np
#creating numpy arrays
arr1 = np.random.randint(1,100, size = 10)
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])

#perform element wise addition 
result = arr1 + arr2
print("arr1:", arr1)
print("\narr2:", arr2)
print("\nElement-wise Addition (arr1 + arr2):")
print(result)

arr1: [94 21 79  3 90  9 59 14 68 94]

arr2: [ 1  2  3  4  5  6  7  8  9 10]

Element-wise Addition (arr1 + arr2):
[ 95  23  82   7  95  15  66  22  77 104]


<h3>52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [86]:
import numpy as np 

#creating numpy arrays
arr1 = np.array([10,9,8,7,6,5,4,3,2,1])
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])

#perform element wise substraction
result = arr1 - arr2
print("arr1:", arr1)
print("\narr2:", arr2)
print("\nElement-wise substraction (arr1 - arr2):")
print(result)

arr1: [10  9  8  7  6  5  4  3  2  1]

arr2: [ 1  2  3  4  5  6  7  8  9 10]

Element-wise substraction (arr1 - arr2):
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


<h3>53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [85]:
import numpy as np

#create numpy arrays
arr1 = np.random.randint(1,50, size=5)
arr2 = np.array([1,2,3,4,5])

#perform element-wise multiplication
result = arr1 * arr2
# Print the result
print("arr1:", arr1)
print("\narr2:", arr2)
print("\nElement-wise multiplication (arr1 * arr2):")
print(result)

arr1: [27 21 49 26 47]

arr2: [1 2 3 4 5]

Element-wise multiplication (arr1 * arr2):
[ 27  42 147 104 235]


<h3>54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [83]:
import numpy as np

# Create NumPy arrays
arr1 = np.array([2, 4, 6, 8, 10])  # Even integers from 2 to 10
arr2 = np.array([1, 2, 3, 4, 5])   # Integers from 1 to 5

# Perform element-wise division
result = arr1 / arr2

# Print the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise division (arr1 / arr2):")
print(result)

arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Element-wise division (arr1 / arr2):
[2. 2. 2. 2. 2.]


<h3>55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [82]:
import numpy as np

# Create NumPy arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])  # Reversed array

# Perform element-wise exponentiation
result = arr1 ** arr2

# Print the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise exponentiation (arr1 ** arr2):")
print(result)

arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Element-wise exponentiation (arr1 ** arr2):
[ 1 16 27 16  5]


<h3> 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
<h3> arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])


In [81]:
import numpy as np

def count_substring_occurrences(arr, substring):
    # Count occurrences of the substring in each element of the array
    counts = np.char.count(arr, substring)
    # Sum up all the counts
    total_count = np.sum(counts)
    return total_count

# Create a NumPy array of strings
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Specify the substring to count
substring = 'hello'

# Count occurrences of the substring
total_occurrences = count_substring_occurrences(arr, substring)

# Print the result
print("Total occurrences of '{}' in the array: {}".format(substring, total_occurrences))

Total occurrences of 'hello' in the array: 3


<h3>57. Write a function that extracts uppercase characters from a NumPy array of strings.

<h3>arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [80]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Extract uppercase characters from each string
uppercase_chars = np.array([''.join([char for char in s if char.isupper()]) for s in arr])

# Print the result
print("Original array:")
print(arr)

print("\nUppercase characters extracted:")
print(uppercase_chars)

Original array:
['Hello' 'World' 'OpenAI' 'GPT']

Uppercase characters extracted:
['H' 'W' 'OAI' 'GPT']


<h3>58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
<h3>arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


In [77]:
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    # Replace occurrences of old_substring with new_substring
    replaced_arr = np.char.replace(arr, old_substring, new_substring)
    return replaced_arr

# Create a NumPy array of strings
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Specify the old and new substrings
old_substring = 'apple'
new_substring = 'fruit'

# Replace occurrences of the old substring with the new substring
result = replace_substring(arr, old_substring, new_substring)

# Print the resulting array
print("Original array:")
print(arr)
print("\nArray after replacement:")
print(result)


Original array:
['apple' 'banana' 'grape' 'pineapple']

Array after replacement:
['fruit' 'banana' 'grape' 'pinefruit']


<h3>59. Write a function that concatenates strings in a NumPy array element-wise.
<h3>arr1 = np.array(['Hello', 'World'])
<h3>arr2 = np.array(['Open', 'AI'])

In [72]:
import numpy as np

# Create two NumPy arrays of strings
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Concatenate the strings element-wise
concatenated_arr = np.char.add(arr1, arr2)

# Print the resulting array
print("Concatenated array:")
print(concatenated_arr)

Concatenated array:
['HelloOpen' 'WorldAI']


<h3> 60. Write a function that finds the length of the longest string in a NumPy array.

<h3>arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [76]:
import numpy as np

def longest_string_length(arr):
    # Find the lengths of all strings in the array
    lengths = np.vectorize(len)(arr)
    # Return the maximum length
    return np.max(lengths)

# Create a NumPy array of strings
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Find the length of the longest string
max_length = longest_string_length(arr)

# Print the result
print("Length of the longest string:", max_length)


Length of the longest string: 9


<h3> 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [68]:
import numpy as np

# Create a NumPy array of 100 random integers between 1 and 1000
data = np.random.randint(1, 1001, size=100)

# Compute mean, median, variance, and standard deviation
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

# Print the results
print("Dataset:")
print(data)

print("\nMean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Dataset:
[140 209 779 463 218 485 750 904 976 199 201 100 185 789 263 897 703 253
 317 657  12 853 335 480 319 898 525 439 779 916 281  67 934 164 199 137
 304 559 218  74 744 343 805  87 428 393 498 551 640 697 925 800 611  73
 190 424 295 619 368 483 769 110 772 325 971 868 343  11 521  22 421 956
 173 485 457 363 533 416 776 670 624 958 438 613 195 708 213 495 553 185
 579  67 162 243 586 547 715 419 356 366]

Mean: 469.39
Median: 448.0
Variance: 72657.23790000001
Standard Deviation: 269.55006566498923


<h3> 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [67]:
import numpy as np

# Generate a NumPy array of 50 random integers between 1 and 100
data = np.random.randint(1, 101, size=50)

# Calculate the 25th and 75th percentiles
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

# Print the array and the percentiles
print("Array:")
print(data)

print("\n25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Array:
[36 18 35 86 41 35 18 15 30 75 61 90 85 12  5 60 83 35 18 95 63 78  2 44
 73  4 88 53 62 74 91 33 18 23 51 77 49 18 54 38 23  3 98  9 11 47 33 82
 77 93]

25th Percentile: 19.25
75th Percentile: 76.5


<h3> 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [66]:
import numpy as np

# Create two arrays representing two sets of variables
array_x = np.array([10, 20, 30, 40, 50])
array_y = np.array([1, 2, 3, 4, 5])

# Compute the correlation coefficient matrix
correlation_matrix = np.corrcoef(array_x, array_y)

# Print the correlation coefficient matrix
print("Correlation coefficient matrix:")
print(correlation_matrix)

Correlation coefficient matrix:
[[1. 1.]
 [1. 1.]]


<h3> 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [65]:
import numpy as np

# Create two matrices
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6]])

matrix_B = np.array([[7, 8],
                     [9, 10],
                     [11, 12]])

# Perform matrix multiplication using np.dot
result_matrix = np.dot(matrix_A, matrix_B)

# Print the resulting matrix
print("Matrix A:")
print(matrix_A)

print("\nMatrix B:")
print(matrix_B)

print("\nResult of Matrix A multiplied by Matrix B:")
print(result_matrix)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of Matrix A multiplied by Matrix B:
[[ 58  64]
 [139 154]]


<h3> 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [64]:
import numpy as np

# Create a NumPy array of 50 integers between 10 and 1000
arr = np.random.randint(10, 1001, size=50)

# Calculate the 10th, 50th (median), and 90th percentiles
percentile_10 = np.percentile(arr, 10)
percentile_50 = np.percentile(arr, 50)  # Median
percentile_90 = np.percentile(arr, 90)

# Calculate the first (25th) and third (75th) quartiles
quartile_1 = np.percentile(arr, 25)
quartile_3 = np.percentile(arr, 75)

# Print the array and the calculated percentiles and quartiles
print("Array:")
print(arr)

print("\n10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", quartile_1)
print("Third Quartile (75th Percentile):", quartile_3)


Array:
[233 778 592 116 820 188 306 958  86 289 633  51 793 565 295 802 535 533
 270 707 382 886 652 433 359 853 914 821  54 697 457 595 376 238 796 838
 466 426 303  99 490 448 357  99 809 819 562 243 734 967]

10th Percentile: 114.30000000000001
50th Percentile (Median): 511.5
90th Percentile: 839.5
First Quartile (25th Percentile): 297.0
Third Quartile (75th Percentile): 789.25


<h3>66. Create a NumPy array of integers and find the index of a specific element.


In [63]:
import numpy as np

# Create a NumPy array of integers
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Define the element to find
element_to_find = 40

# Find the index of the specific element
indices = np.where(arr == element_to_find)

# Print the indices
print("Index of element", element_to_find, ":", indices[0])

Index of element 40 : [3]


<h3> 67. Generate a random NumPy array and sort it in ascending order.


In [62]:
import numpy as np

# Generate a random NumPy array of shape (10,) with integers between 1 and 100
random_arr = np.random.randint(1, 101, size=10)

# Print the original random array
print("Original array:")
print(random_arr)

# Sort the array in ascending order
sorted_arr = np.sort(random_arr)

# Print the sorted array
print("\nSorted array in ascending order:")
print(sorted_arr)

Original array:
[  9   9   1 100  66  22  41  42  67  71]

Sorted array in ascending order:
[  1   9   9  22  41  42  66  67  71 100]


<h3>68. Filter elements >20  in the given NumPy array.
<h3>arr = np.array([12, 25, 6, 42, 8, 30])


In [61]:
import numpy as np

# Create a NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements which are ≥ 20 and ≤ 40
filtered_arr = arr[(arr > 20)]

# Print the filtered array
print("Filtered array:")
print(filtered_arr)

Filtered array:
[25 42 30]


<h3> 69. Filter elements which are divisible by 3 from a given NumPy array.
<h3> arr = np.array([1, 5, 8, 12, 15])

In [59]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements which are divisible by 3
filtered_arr = arr[arr % 3 == 0]

# Print the filtered array
print("Filtered array (divisible by 3):")
print(filtered_arr)

Filtered array (divisible by 3):
[12 15]


<h3> 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
<h3>arr = np.array([10, 20, 30, 40, 50])

In [58]:
import numpy as np

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements which are ≥ 20 and ≤ 40
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

# Print the filtered array
print("Filtered array:")
print(filtered_arr)

Filtered array:
[20 30 40]


<h3> 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
<h3>arr = np.array([1, 2, 3])

In [57]:
import numpy as np

# Create a NumPy array with default dtype
arr = np.array([1, 2, 3])

# Check the byte order of the array
byteorder = arr.dtype.byteorder

# Print the byte order
print("Byte order of the array:", byteorder)

Byte order of the array: =


<h3> 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
    <h3> arr = np.array([1, 2, 3], dtype=np.int32)

In [56]:
import numpy as np

# Create a NumPy array with dtype np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array
print("Original array:")
print(arr)

# Perform byte swapping in place
arr.byteswap(inplace=True)

# Print the array after byte swapping
print("\nArray after byte swapping:")
print(arr)


Original array:
[1 2 3]

Array after byte swapping:
[16777216 33554432 50331648]


<h3> 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
<h3> arr = np.array([1, 2, 3], dtype=np.int32)

In [55]:
# used chatgpt to solve this question

import numpy as np

# Create a NumPy array with dtype np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap the byte order of the array without modifying the original array
swapped_arr = arr.byteswap().newbyteorder()

# Display the original array and the byte-swapped array
print("Original array:")
print(arr)

print("\nByte-swapped array:")
print(swapped_arr)

[1 2 3]
Original array:
[1 2 3]

Byte-swapped array:
[1 2 3]


<h3>74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

In [53]:
# used chatgpt to solve this question
import numpy as np
import sys

# Create a NumPy array with dtype np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Get the byte order of the system
system_endianness = '<' if sys.byteorder == 'little' else '>'

# Print the system endianness
print("System endianness:", sys.byteorder)

# Get the byte order of the array
array_byteorder = arr.dtype.byteorder

# Determine the desired byte order for swapping
if array_byteorder == '=':
    # The array is in native byte order
    if sys.byteorder == 'little':
        desired_byteorder = '>'
    else:
        desired_byteorder = '<'
elif array_byteorder == '<':
    # The array is in little-endian byte order
    desired_byteorder = '>'
elif array_byteorder == '>':
    # The array is in big-endian byte order
    desired_byteorder = '<'
else:
    # Unknown byte order, handle as needed
    desired_byteorder = '='

# Swap the byte order if necessary
if desired_byteorder != '=':
    swapped_arr = arr.byteswap().newbyteorder(desired_byteorder)
else:
    swapped_arr = arr

# Display the original array and the conditionally byte-swapped array
print("\nOriginal array:")
print(arr)

print("\nConditionally byte-swapped array:")
print(swapped_arr)


System endianness: little

Original array:
[1 2 3]

Conditionally byte-swapped array:
[1 2 3]


<h3> 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
    arr = np.array([1, 2, 3], dtype=np.int32)


In [52]:
# used chatgpt to solve this question
import numpy as np

# Create a NumPy array with dtype np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the byte order of the array
byteorder = arr.dtype.byteorder

# Print the byte order
print("Byte order of the array:", byteorder)

# Check if byte swapping is necessary
if byteorder == '=':
    print("The array is in the native byte order.")
elif byteorder == '<':
    print("The array is in little-endian byte order.")
elif byteorder == '>':
    print("The array is in big-endian byte order.")
else:
    print("The byte order is unknown.")

# Optionally, check and display the byte-swapped version of the array
swapped_arr = arr.byteswap().newbyteorder()
print("\nOriginal array:")
print(arr)
print("Byte-swapped array:")
print(swapped_arr)

Byte order of the array: =
The array is in the native byte order.

Original array:
[1 2 3]
Byte-swapped array:
[1 2 3]


<h3> 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [50]:
import numpy as np

# Create a NumPy array 'arr1' with values from 1 to 10
arr1 = np.arange(1, 11)
print("\nOriginal 'arr1':")
print(arr1)

# Create a copy of 'arr1' named 'copy_arr'
copy_arr = arr1.copy()
print("\nCopy of 'arr1':")
print(copy_arr)

# Modify an element in 'copy_arr'
copy_arr[0] = 99  # Change the first element to 99
print("\nModified 'copy_arr':")
print(copy_arr)

# Display the original array and the modified copy
print("\nOriginal 'arr1' after modifying 'copy_arr':")
print(arr1)


Original 'arr1':
[ 1  2  3  4  5  6  7  8  9 10]

Copy of 'arr1':
[ 1  2  3  4  5  6  7  8  9 10]

Modified 'copy_arr':
[99  2  3  4  5  6  7  8  9 10]

Original 'arr1' after modifying 'copy_arr':
[ 1  2  3  4  5  6  7  8  9 10]


<h3> 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [47]:
import numpy as np

# Create a 2D NumPy array 'matrix' of shape (3, 3) with random integers
matrix = np.random.randint(1, 10, size=(3, 3))
print("\nOriginal Matrix")
print(matrix)

# Extract a slice 'view_slice' from 'matrix'
view_slice = matrix[1:, 1:]  # Extracting a sub-array from the original matrix
print("\nSliced 'view_slice' from 'matrix'")
print(view_slice)

# Modify an element in 'view_slice'
view_slice[0, 0] = 99  # Change the top-left element of the slice
print("\nModified 'view_slice':")
print(view_slice)

# Display the original matrix and the modified slice
print("\nOriginal 'matrix' after modifying 'view_slice':")
print(matrix)


Original Matrix
[[4 2 9]
 [4 5 9]
 [3 4 4]]

Sliced 'view_slice' from 'matrix'
[[5 9]
 [4 4]]

Modified 'view_slice':
[[99  9]
 [ 4  4]]

Original 'matrix' after modifying 'view_slice':
[[ 4  2  9]
 [ 4 99  9]
 [ 3  4  4]]


<h3> 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [37]:
import numpy as np

# Create a NumPy array 'array_a' of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)
print("\nOriginal array_a")
print(array_a)

# Extract a slice 'view_b' from 'array_a'
view_b = array_a[1:3, 1:3]  # This slice is a view of the original array
print("\nslice 'view_b' from 'array_a'")
print(view_b)

# Broadcast the addition of 5 to sliced 'view_b'
view_b += 5
print("\nModified slice 'view_b':")
print(view_b)

# Display the original array and the modified slice
print("\nOriginal 'array_a' after modifying 'view_b':")
print(array_a)


Original array_a
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

slice 'view_b' from 'array_a'
[[5 6]
 [8 9]]

Modified slice 'view_b':
[[10 11]
 [13 14]]

Original 'array_a' after modifying 'view_b':
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]


<h3>79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [39]:
import numpy as np

# Create a NumPy array 'orig_array' of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)
print("\nOriginal Array of shape (2,4)")
print(orig_array)

# Create a reshaped view of 'orig_array' with shape (4, 2)
reshaped_view = orig_array.reshape(4, 2)
print("\nReshaped View of Array of shape (4,2)")
print(reshaped_view)

# Modify an element in 'reshaped_view'
reshaped_view[0, 0] = 99  # Change the first element to 99
print("\nChange in 'reshaped_view':")
print(reshaped_view)

# Display the original array and the reshaped view
print("\nOriginal 'orig_array' after modifying 'reshaped_view':")
print(orig_array)
print("\n Yes, change in reshaped_view reflects in orig_array.") 


Original Array of shape (2,4)
[[1 2 3 4]
 [5 6 7 8]]

Reshaped View of Array of shape (4,2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Change in 'reshaped_view':
[[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]

Original 'orig_array' after modifying 'reshaped_view':
[[99  2  3  4]
 [ 5  6  7  8]]

 Yes, change in reshaped_view reflects in orig_array.


<h3> 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [24]:
import numpy as np

# Create a NumPy array 'data' of shape (3, 4) with random integers between 1 and 10
data = np.random.randint(1, 11, size=(3, 4))

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Modify an element in 'data_copy'
if data_copy.size > 0:
    data_copy[0] = 99  # Change the first element to 99

# Display the original 'data' array
print("Original 'data' array:")
print(data)

# Display the modified 'data_copy' array
print("\nModified 'data_copy' array:")
print(data_copy)

# Verify if the original 'data' is affected
print("\nCheck if original 'data' is affected:")
print(data)

Original 'data' array:
[[10  3 10  8]
 [ 3 10 10  7]
 [ 9  9 10 10]]

Modified 'data_copy' array:
[99 10  8 10 10  7  9  9 10 10]

Check if original 'data' is affected:
[[10  3 10  8]
 [ 3 10 10  7]
 [ 9  9 10 10]]


<h3> 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [ ]:
import numpy as np

# Create two matrices A and B of identical shape
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Perform addition of matrices A and B
C_add = A + B

# Perform subtraction of matrices A and B
C_sub = A - B

# Display the matrices and their results
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nA + B (Addition):")
print(C_add)

print("\nA - B (Subtraction):")
print(C_sub)

<h3> 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [22]:
# importing the module 
import numpy as np 

# creating two matrices 
C = np.matrix([[1, 2], [2, 3], [4, 5]])
D = np.matrix([[4, 5, 1], [6, 7, 2]])
print("Matrix C :") 
print(C) 
print("\nMatrix D :") 
print(D) 

# computing product 
result = np.dot(C, D) 

# printing the result 
print("\nThe matrix multiplication is :") 
print(result)

Matrix C :
[[1 2]
 [2 3]
 [4 5]]

Matrix D :
[[4 5 1]
 [6 7 2]]

The matrix multiplication is :
[[16 19  5]
 [26 31  8]
 [46 55 14]]


<h3> 83. Create a matrix `E` and find its transpose.

In [19]:
# import the important module in python 
import numpy as np 
			
# make matrix with numpy 
E = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]') 

# Displaying the Matrix 
print("\nE = ") 
print(E)

# applying matrix.transpose() method 
trans = E.transpose() 

print("\nTranspose of given 3X3 square matrix:") 
print(trans)


E = 
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

Transpose of given 3X3 square matrix:
[[ 4 12  4]
 [ 1  3  5]
 [ 9  1  6]]


<h3> 84. Generate a square matrix `F` and compute its determinant.

In [13]:
# importing Numpy package 
import numpy as np 

# creating a 3X3 Numpy matrix 
F = np.array([[56, 75, 35], 
					[70, 34, 20], 
					[19, 47, 71]]) 

# Displaying the Matrix 
print("F = ") 
print(F) 

# calculating the determinant of matrix 
det = np.linalg.det(F) 

print("\nDeterminant of given 3X3 square matrix:") 
print(int(det))

F = 
[[56 75 35]
 [70 34 20]
 [19 47 71]]

Determinant of given 3X3 square matrix:
-169166


<h3> 85. Create a square matrix `G` and find its inverse.

In [16]:
# Import required package
import numpy as np

# Taking a 3 * 3 matrix
G = np.array([[9, 2, 1],
			[4, -6, 8],
			[1, 8, 7]])
# Displaying the Matrix 
print("G = ") 
print(G)

# Calculating the inverse of the matrix
inv = np.linalg.inv(G)

print("\nInverse of given 3X3 square matrix:") 
print(inv)


G = 
[[ 9  2  1]
 [ 4 -6  8]
 [ 1  8  7]]

Inverse of given 3X3 square matrix:
[[ 0.11087866  0.00627615 -0.02301255]
 [ 0.0209205  -0.06485356  0.07112971]
 [-0.03974895  0.07322176  0.06485356]]
